name:  Docker Image Create & Push To ACR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag frontend-image:latest

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Tag the Docker image
      run: |
        IMAGE_TAG=${{ secrets.ACR_NAME }}.azurecr.io/frontend-image:latest
        docker tag frontend-image:latest $IMAGE_TAG
    - name: Push the Docker image to ACR
      run: |
        IMAGE_TAG=${{ secrets.ACR_NAME }}.azurecr.io/frontend-image:latest
        docker push $IMAGE_TAG

    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Docker Image Build and Push Success
        body: The Docker image has been successfully built and pushed to Azure Container Registry.
        to: ${{ secrets.EMAIL_USERNAME }}
        from: ${{ secrets.EMAIL_USERNAME }}
