name:  Docker Image Create & Push To ACR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag frontend-image:latest

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Tag the Docker image
      run: |
        IMAGE_TAG=${{ secrets.ACR_NAME }}.azurecr.io/frontend-image:latest
        docker tag frontend-image:latest $IMAGE_TAG
    - name: Push the Docker image to ACR
      run: |
        IMAGE_TAG=${{ secrets.ACR_NAME }}.azurecr.io/frontend-image:latest
        docker push $IMAGE_TAG
